#!/bin/bash

ANNOUNCED_IP=${ANNOUNCED_IP}
ANNOUNCED_PORT=${ANNOUNCED_PORT}
GROUP_NAME=${GROUP_NAME}
QUORUM=${QUORUM}
REDIS_PORT=${REDIS_PORT}
SENTINEL_CONFIGURATION_FILE=/etc/sentinel.conf

echo "port ${ANNOUNCED_PORT}" > $SENTINEL_CONFIGURATION_FILE
echo "sentinel monitor $GROUP_NAME $ANNOUNCED_IP $REDIS_PORT $QUORUM" >> $SENTINEL_CONFIGURATION_FILE
echo "sentinel down-after-milliseconds $GROUP_NAME 60000" >> $SENTINEL_CONFIGURATION_FILE
echo "sentinel failover-timeout $GROUP_NAME 180000" >> $SENTINEL_CONFIGURATION_FILE
echo "sentinel parallel-syncs $GROUP_NAME 1" >> $SENTINEL_CONFIGURATION_FILE

/usr/local/bin/redis-sentinel $SENTINEL_CONFIGURATION_FILE
